In [1]:
import pickle
import numpy as np

In [6]:
def unpickle(file):
  with open(file, 'rb') as f:
    data = pickle.load(f, encoding='bytes')
  return data

In [17]:
input = unpickle('./data/cifar-10-batches-py/data_batch_1')

In [18]:
input.keys()

dict_keys([b'batch_label', b'labels', b'data', b'filenames'])

In [19]:
data = np.array(input[b'data'])
labels = np.array(input[b'labels'])

In [22]:
data.shape

(10000, 3072)

In [24]:
a = np.array([[1, 2, 3,], [4, 5, 6], [7, 8, 9]])

In [25]:
a/10

array([[0.1, 0.2, 0.3],
       [0.4, 0.5, 0.6],
       [0.7, 0.8, 0.9]])

In [28]:
np.zeros((30720,)).shape

(30720,)

In [37]:
def _softmax(x):
    """Calculates the softmax of a vector

    Args:
        x (ndarray[uint8]): An ndarray of uint8

    Returns:
        [ndarray[uint8]]: Vector after applying softmax
    """
    x = np.exp(x)
    
    # Calculate the sum of the elements
    sum_of_elements = np.sum(x)

    # Divide each element by the sum of the elements
    x = x / sum_of_elements

    # Return the vector (applied softmax)
    return x

In [38]:
_softmax(np.array([1, 2,3, 4, 5, 6, 7, 8, 9, 0]))

array([2.12062451e-04, 5.76445508e-04, 1.56694135e-03, 4.25938820e-03,
       1.15782175e-02, 3.14728583e-02, 8.55520989e-02, 2.32554716e-01,
       6.32149258e-01, 7.80134161e-05])

In [34]:
np.sum(np.array([1,2, 3, 4, 5, 6, 7,8 ,9, 0]))

45

In [35]:
np.array([1,2, 3, 4, 5, 6, 7,8 ,9, 0]) / 45

array([0.02222222, 0.04444444, 0.06666667, 0.08888889, 0.11111111,
       0.13333333, 0.15555556, 0.17777778, 0.2       , 0.        ])

In [36]:
np.exp([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 1.00000000e+00])

In [39]:
test = np.empty((3, 2))
test

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [40]:
test[0] = [1, 2]
test

array([[1., 2.],
       [0., 0.],
       [0., 0.]])

In [41]:
np.array([1,2 ,3]).T * np.array([1, 2, 3])

array([1, 4, 9])

In [42]:
-1

-1

In [43]:
- 1

-1