# **Pytorch Tutorial**
(Mostly follows Pytorch Blitz Tutorial by Soumith Chintala: https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html)

Before starting, change the Runtime to GPU. ``Menu > Runtime > Change runtime type > GPU``



##**Tensors**

Tensors are similar to NumPy’s ndarrays, with the addition being that Tensors can also be used on a GPU to accelerate computing.

#### Import Libraries

In [1]:
%matplotlib inline
import torch
import numpy as np

#### Construct tensor directly from data. (**torch.tensor**)

In [2]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [3]:
y = np.array([[3., 1.], [1.5, 2.5]])
z = torch.tensor(y)
print(z)

tensor([[3.0000, 1.0000],
        [1.5000, 2.5000]], dtype=torch.float64)


#### Other ways to create tensors. (**torch.rand, torch.zeros, torch.ones, torch.randn**)

In [4]:
x = torch.rand(5, 3)
print(x)

tensor([[0.0263, 0.1173, 0.3247],
        [0.9361, 0.2584, 0.5100],
        [0.4420, 0.4507, 0.3839],
        [0.8541, 0.5875, 0.0779],
        [0.3324, 0.4437, 0.0442]])


In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [6]:
x = torch.ones(5, 3, dtype=torch.float32)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [7]:
x = torch.randn(5, 3, dtype=torch.float64)
print(x)

tensor([[ 0.1359,  1.2255,  0.0099],
        [ 0.7085,  0.5375, -0.1357],
        [ 0.0110, -1.0421, -0.5249],
        [ 0.1140,  1.0507, -0.1843],
        [-0.0017, -1.5810, -0.7078]], dtype=torch.float64)


In [8]:
print(x)
print(x.dtype)

tensor([[ 0.1359,  1.2255,  0.0099],
        [ 0.7085,  0.5375, -0.1357],
        [ 0.0110, -1.0421, -0.5249],
        [ 0.1140,  1.0507, -0.1843],
        [-0.0017, -1.5810, -0.7078]], dtype=torch.float64)
torch.float64


#### Access properties of tensors (**size(), dtype**)

In [9]:
print(x.size)
print(x.shape)

<built-in method size of Tensor object at 0x7f981a998590>
torch.Size([5, 3])


#### Tensor Operations (**add, matmul**)

In [10]:
x = torch.ones([2, 4], dtype=torch.float32)
y = torch.rand([2, 4], dtype=torch.float32)
print("x: ", x)
print("y: ", y)

a = x+y     # Tensor addition
b = torch.add(x,y)

c = torch.empty([2, 4])
torch.add(x, y, out=c)    # Providing output tensor as argument

print("a: ", a)
print("b: ", b)
print("c: ", c)

x.add_(y)   # in-place Addition
print("x: ", x)

x:  tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])
y:  tensor([[0.8075, 0.4142, 0.4502, 0.4154],
        [0.7588, 0.6275, 0.8487, 0.5730]])
a:  tensor([[1.8075, 1.4142, 1.4502, 1.4154],
        [1.7588, 1.6275, 1.8487, 1.5730]])
b:  tensor([[1.8075, 1.4142, 1.4502, 1.4154],
        [1.7588, 1.6275, 1.8487, 1.5730]])
c:  tensor([[1.8075, 1.4142, 1.4502, 1.4154],
        [1.7588, 1.6275, 1.8487, 1.5730]])
x:  tensor([[1.8075, 1.4142, 1.4502, 1.4154],
        [1.7588, 1.6275, 1.8487, 1.5730]])


In [11]:
x = torch.tensor(np.array([[1., 2.],
                           [1., 2.]]))
y = torch.tensor(np.array([[1., 2.],
                           [1., 2.]]))
print(torch.matmul(x,y))    # Results in matrix multiplication

tensor([[3., 6.],
        [3., 6.]], dtype=torch.float64)


In [12]:
print(x * y) #element-wise multiplication

tensor([[1., 4.],
        [1., 4.]], dtype=torch.float64)


In [13]:
print(y@x) #matrix multiplication

tensor([[3., 6.],
        [3., 6.]], dtype=torch.float64)


#### Indexing, Reshaping, Numpy

In [ ]:
x = torch.rand([5,6])
print(x)
print(x[:, 1])

In [ ]:
print(x)
y = x.reshape(2, 3, 5)
z = x.reshape(-1, 15)  # the size -1 is inferred from other dimensions
a = x.view(5, -1) # view can also be used to reshape the array
print(y)
print(f'shape of y: {y.shape}, shape of z: {z.shape}, shape of a: {a.shape}')

For one-element tensors, we can use `.item()` to get its values as a Python number. This is often used while printing/plotting the value of a neural network loss, which would otherwise be a tensor.

In [ ]:
x = torch.rand(1)
print(x)
print(x.item())

It's easy to convert between Torch Tensor and Numpy array.  
Note: They share underlying memory locations on CPU and changing one will change the other.

In [ ]:
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

In [ ]:
a.add_(1)   # in-place means the same memory location is updated.
print(b)

In [ ]:
a = a + 1   # This creates the tensor 'a' at a new memory location.
print(b)


In [ ]:
print(a)

In [ ]:
a = np.ones(5)
b = torch.tensor(a)     # This creates a tensor which does not share the memory location
c = torch.from_numpy(a)   # This is the way to create a tensor using the same memory location as np array
np.add(a, 1, out=a)   # Changing the numpy array
print(b)
print(c)

#### CUDA Tensors

CUDA is a parallel computing platform and API that enables the use of GPU.

In [ ]:
print(torch.cuda.is_available())

In [ ]:
x = torch.rand([2,2])
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.rand([2,2], device=device)  # directly create a tensor on GPU
    print(y)

    x = x.to(device)    # Useful command to convert tensors to GPU
    z = x + y
    print(z)
    print(z.cpu())    # Convert back to CPU

Let's look at the speedup if we use GPU for complex operations.
(Borrowed from: [Edureka YouTube Tutorial](https://www.youtube.com/watch?v=XriwHXfLi6M&ab_channel=edureka%21) )

In [ ]:
import time

d = 5000

# Numpy
A = np.random.rand(d, d).astype(np.float32)
B = np.random.rand(d, d).astype(np.float32)

#on the CPU
AA = torch.tensor(A)
BB = torch.tensor(B)
t = time.time()
CC = torch.matmul(AA, BB)
print(time.time() - t)

# Torch with GPU
AA = torch.tensor(A).cuda()
BB = torch.tensor(B).cuda()
t = time.time()
CC = torch.matmul(AA, BB)
print(time.time() - t)

#### Summary

1. **Creating** tensors: torch.tensor, torch.zeros, torch.ones, torch.rand, torch.randn
2. **Accessing** properties of tensors: size(), dtype
3. Tensor **operations**: add, matmul
4. Indexing, Reshaping, interaction with **Numpy**
5. Using tensors on **GPU**!

Next, how PyTorch uses tensors to enable **automatic differentiation**.

#### **Exercises**

(1) You can create uninitialized tensors, whose values are assigned based on whatever the allocated memory stores at that time. Read the documentation and try **torch.empty**

(2) You can create tensors based on existing tensors. These methods will reuse properties of the input tensor, e.g. dtype, unless new values are provided by user.  
For instance, try:
```
x = torch.tensor([0, 0], dtype=torch.int32)
y = x.new_ones(3, 2)
print(y)
print(y.dtype)
```

Read and try the documentation of **new_zeros, new_empty, randn_like** to see what they can do!


##**Autograd**

Central to all neural networks in PyTorch is the ``autograd`` package.

The ``autograd`` package provides automatic differentiation for all operations
on Tensors.

(Refer to Slides)

----

**Computation Graph**  
``Tensor`` and ``Function`` are interconnected and build up an acyclic
graph, that encodes a complete history of computation. Each tensor has
a ``.grad_fn`` attribute that references a ``Function`` that has created
the ``Tensor`` (except for Tensors created by the user - their
``grad_fn is None``).

----


If you set a tensor's attribute ``.requires_grad`` as ``True``, it starts to track all operations on it. When you finish your computation you can call ``backward()`` and have all the gradients computed automatically. The gradient for this tensor will be accumulated into ``.grad`` attribute.

In [ ]:
x = np.array([[1., 1.],
              [1., 1.]])
x = torch.tensor(x, requires_grad=True)
print(x)

Let's see what happens when we create a new tensor using a function on x.

In [ ]:
y = x + 2
print(y)
print(y.grad_fn)

Each tensor has a ``.grad_fn`` attribute that references a ``Function`` that has created the ``Tensor``.
If you want to compute the derivatives, you can call ``.backward()`` on
a ``Tensor``.

In [ ]:
z = y * y * 3
out = z.mean()

# Clear gradients before calling backward
out.backward()
print(out)
print(x.grad)

You should have got a matrix of ``4.5``. Let’s call the ``out``
*Tensor* “$o$”.  
We have that $o = \frac{1}{4}\sum_i z_i$,  
$z_i = 3(x_i+2)^2$ and $z_i\bigr\rvert_{x_i=1} = 27$.  
Therefore,
$\frac{\partial o}{\partial x_i} = \frac{3}{2}(x_i+2)$, hence
$\frac{\partial o}{\partial x_i}\bigr\rvert_{x_i=1} = \frac{9}{2} = 4.5$.

#### **What autograd is actually doing.**

(Refer to Slides)

Mathematically, if you have a vector valued function $\vec{y}=f(\vec{x})$,
then the gradient of $\vec{y}$ with respect to $\vec{x}$
is a Jacobian matrix:

\begin{align}J=\left(\begin{array}{ccc}
   \frac{\partial y_{1}}{\partial x_{1}} & \cdots & \frac{\partial y_{1}}{\partial x_{n}}\\
   \vdots & \ddots & \vdots\\
   \frac{\partial y_{m}}{\partial x_{1}} & \cdots & \frac{\partial y_{m}}{\partial x_{n}}
   \end{array}\right)\end{align}

Generally speaking, ``torch.autograd`` is an engine for computing
vector-Jacobian product. That is, **given any vector**
$v=\left(\begin{array}{cccc} v_{1} & v_{2} & \cdots & v_{m}\end{array}\right)^{T}$,
compute the product $v^{T}\cdot J$.

This is useful to realize the chain rule in Neural Network **backpropagation**.

---------------------------------------------------

#### **Chain Rule in backpropagation**

If $v$ happens to be
the gradient of a scalar function $l=g\left(\vec{y}\right)$,
that is,
$v=\left(\begin{array}{ccc}\frac{\partial l}{\partial y_{1}} & \cdots & \frac{\partial l}{\partial y_{m}}\end{array}\right)^{T}$,
then by the chain rule, the vector-Jacobian product would be the
gradient of $l$ with respect to $\vec{x}$:

\begin{align}J^{T}\cdot v=\left(\begin{array}{ccc}
   \frac{\partial y_{1}}{\partial x_{1}} & \cdots & \frac{\partial y_{m}}{\partial x_{1}}\\
   \vdots & \ddots & \vdots\\
   \frac{\partial y_{1}}{\partial x_{n}} & \cdots & \frac{\partial y_{m}}{\partial x_{n}}
   \end{array}\right)\left(\begin{array}{c}
   \frac{\partial l}{\partial y_{1}}\\
   \vdots\\
   \frac{\partial l}{\partial y_{m}}
   \end{array}\right)=\left(\begin{array}{c}
   \frac{\partial l}{\partial x_{1}}\\
   \vdots\\
   \frac{\partial l}{\partial x_{n}}
   \end{array}\right)\end{align}

(Note that $v^{T}\cdot J$ gives a row vector which can be
treated as a column vector by taking $J^{T}\cdot v$.)

This characteristic of vector-Jacobian product makes it very
convenient to feed external gradients into a model that has
non-scalar output.


In [ ]:
# backward with vector v
x = torch.randn(3, requires_grad=True)
y = x * 2
y = y * 2

v = torch.tensor([0.1, 1.0, 10], dtype=torch.float32)

y.backward(v)

print(x.grad)

**Note on backward()**: 
We don't usually manipulate the gradients directly. Pytorch provides optimizers to take care of it. They update the weights of the neural network.

#### **Stopping gradients**
Sometimes we don't want to compute gradients in some parts of the execution. e.g. during evaluation on test data, we don't need the gradients. We can do this using:

``with torch.no_grad()`` or ``.detach()``

In [ ]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
	print((x ** 2).requires_grad)

In [ ]:
y = x.detach()    # Creates a tensor that is detached from the computation graph.
print(y.requires_grad)

##**Neural Networks**

Neural networks can be constructed using the ``torch.nn`` package.

A neural network is defined by an ``nn.Module``.
A module contains a set of neural layers and their weights. A method ``forward(input)`` defines a function $f(x)$ that returns the ``output``.

----------------------


A typical **training procedure** for a neural network is as follows:

- **Define** the neural network that has some learnable parameters (or
  weights)
- Iterate over a **dataset** of inputs
- **Forward pass**: Process input through the network
- Compute the **loss** (how far is the output from being correct)
- **Backward pass**: Propagate gradients back into the network’s parameters
- **Update** the weights of the network, typically using a simple update rule:
  ``weight = weight - learning_rate * gradient``

#### Models

Layers defined in a module will be automatically added to the computation graph.

1. Your custom module should inherit from `nn.Module`.  
2. `super().__init__()` should be added in your `__init__()` method. Define your neural network layers here.  
3. You need to implement your own `forward()` function which describes the forward pass. `backward` is automatically defined for you using `autograd`.

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

# Define a 2-layer MLP
class MLP(nn.Module):
  def __init__(self, input_dim=20, hidden_dim=32, output_dim=15):
      super().__init__()

      self.linear_1 = nn.Linear(input_dim, hidden_dim, bias=True)
      self.relu = nn.ReLU()
      self.linear_2 = nn.Linear(hidden_dim, output_dim, bias=True)
    
  def forward(self, input):
    # Define forward pass (input -> linear module -> relu -> linear module -> output)
      # [10, 20]
      x = self.linear_1(input) # [10, 32]
      x = self.relu(x)  # [10, 32]
      x = self.linear_2(x)  # [10, 15]
      return x


Inputs should always be in the form of mini-batches. Single samples are not supported. The first dimension corresponds to the mini-batch dimension. You can use ``input.unsqueeze(0)`` to add a fake batch dimension to the first axis.

In [ ]:
x = torch.randn(5)
print(x.size(), x.unsqueeze(0).size())

Next, let's create an instance of the neural network.

In [ ]:
# Defining parameters, model, input
in_dim = 20
out_dim = 15
hidden_dim = 32
batch_size = 10

model = MLP(in_dim, hidden_dim, out_dim)

input = torch.randn(batch_size, in_dim)

Calling a neural network module with its input ``model(input)`` directly calls the forward function.

In [ ]:
output = model(input)   # This calls the forward function. Same as model.forward(input)

print(model)
print(output.size())
print(output)

In [ ]:
params = list(model.parameters())
print(len(params))
print(params[0].size(), params[1].size(), params[2].size(), params[3].size())   # Access parameters using the list
print(model.linear_1.weight.size(), model.linear_1.bias.size())    # Access parameters using module name
print(model.linear_1.bias)

#### Backward pass
To backpropagate the gradients, we use the ``backward()`` function.
You need to clear the existing gradients though, else gradients will be
accumulated to existing gradients.

In [ ]:
# Perform backward pass with a vector v
model.zero_grad()
print(model.linear_1.bias.grad)
v = torch.randn(batch_size, out_dim)

output.backward(v)
print(model.linear_1.bias.grad)


Before seeing how neural networks work with a loss function, let's recap the classes we've seen so far.

**Recap:**
  -  ``torch.Tensor`` - A *multi-dimensional array* with support for autograd
     operations like ``backward()``. Also *holds the gradient* w.r.t. the
     tensor.
  -  ``nn.Module`` - Neural network module. *Convenient way of
     encapsulating parameters*, with helpers for moving them to GPU,
     exporting, loading, etc.
  -  ``nn.Parameter`` - A kind of Tensor, that is *automatically
     registered as a parameter when assigned as an attribute to a*
     ``Module``.
  -  ``autograd.Function`` - Implements *forward and backward definitions
     of an autograd operation*. Every ``Tensor`` operation creates at
     least a single ``Function`` node that connects to functions that
     created a ``Tensor`` and *encodes its history*.
     This can be accessed using ``grad_fn``.
    
----

**At this point, we have covered:**
  -  Defining a neural network
  -  Processing inputs and calling backward

**Still Left:**
  -  Computing the loss
  -  Updating the weights of the network

#### Loss Function

A loss function takes the (output, target) pair of inputs, and computes a
value that estimates how far away the output is from the target.

There are several different
`loss functions <https://pytorch.org/docs/nn.html#loss-functions>`_ under the
nn package .
A simple loss is: ``nn.MSELoss`` which computes the mean-squared error
between the input and the target. For example:

In [ ]:
# Compute loss
output = model(input) # Forward
target = torch.randn(batch_size, out_dim)  # a dummy target, for example
criterion = nn.MSELoss()  # loss function

loss = criterion(output, target)  # compute the loss
print(loss)

When we call loss.backward(), the whole graph is differentiated w.r.t. the loss, and all Tensors in the graph that have ``requires_grad=True`` will have their ``.grad`` Tensor accumulated with the gradient.

For illustration, let us follow a **few steps backward**:

In [ ]:
print(loss.grad_fn)
print(loss.grad_fn.next_functions[0][0])  # Linear Layer

To **backpropagate** the error using the loss function, all we have to do is to ``loss.backward()``.
You need to clear the existing gradients though, else gradients will be
accumulated to existing gradients.

In [ ]:
# Loss backpropagation
model.zero_grad()   # Because each tensor may already contain some gradients, which we do not want to be accumulated
print(model.linear_1.bias.grad)

loss.backward()
print(model.linear_1.bias.grad)

#### Update the weights

Now the computed gradients can be used to perform a step of gradient descent to update the weights.

The simplest update rule used in practice is the Stochastic Gradient
Descent (SGD):

     weight = weight - learning_rate * gradient

In [ ]:
# Update weights using accumulated gradients
learning_rate = 0.01

print(model.linear_1.bias[0])
print(model.linear_1.bias.grad[0])

for f in model.parameters():
    f.detach().sub_(learning_rate * f.grad)

print(model.linear_1.bias[0])

**Optimizers**

As you use neural networks, you want to use various different update rules such as SGD, Nesterov-SGD, Adam, RMSProp, etc.  
``torch.optim`` implements all these methods. Using it is very simple:

In [ ]:
import torch.optim as optim

# create your optimizer
optimizer = optim.SGD(model.parameters(), lr=0.01)

In [ ]:
# Using optimizer in your training loop
optimizer.zero_grad()
output = model(input)

loss = criterion(output, target)

loss.backward()

print(model.linear_1.bias[0])
optimizer.step()  # Does the update
print(model.linear_1.bias[0])

##**Training Image Classifier**

#### **Data**

Generally, when you have to deal with image, text, audio or video data,
you can use standard python packages that load data into a numpy array.
Then you can convert this array into a ``torch.*Tensor``.

-  For images, packages such as Pillow, OpenCV are useful
-  For audio, packages such as scipy and librosa
-  For text, either raw Python or Cython based loading, or NLTK and
   SpaCy are useful
   
Specifically for vision, we can use a package called
``torchvision``, that has data loaders for common datasets such as
Imagenet, CIFAR10, MNIST, etc. and data transformers for images. These can be accessed using ``torchvision.datasets`` and ``torch.utils.data.DataLoader``.

This provides a huge convenience and avoids writing boilerplate code.

-----
**CIFAR10**

For this tutorial, we will use the CIFAR10 dataset.
It has the classes: ‘airplane’, ‘automobile’, ‘bird’, ‘cat’, ‘deer’,
‘dog’, ‘frog’, ‘horse’, ‘ship’, ‘truck’. The images in CIFAR-10 are of
size 3x32x32, i.e. 3-channel color images of 32x32 pixels in size.

https://pytorch.org/tutorials/_images/cifar10.png

-----

**Training an image classifier**

We will do the following steps in order:

1. Load and normalizing the CIFAR10 training and test datasets using
   ``torchvision``
2. Define a Convolutional Neural Network
3. Define a loss function
4. Train the network on the training data
5. Test the network on the test data

----

**1. Loading and normalizing CIFAR10**

Using ``torchvision``, it’s extremely easy to load CIFAR10.



In [ ]:
import torch
import torchvision
import torchvision.transforms as transforms

The output of torchvision datasets are PILImage images of range [0, 1].
We **transform** them to Tensors of normalized range [-1, 1].



In [ ]:
transform = transforms.Compose(
    [transforms.ToTensor(),
     transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))])

trainset = torchvision.datasets.CIFAR10(root='./data', train=True,
                                        download=True, transform=transform)


testset = torchvision.datasets.CIFAR10(root='./data', train=False,
                                       download=True, transform=transform)


classes = ('plane', 'car', 'bird', 'cat',
           'deer', 'dog', 'frog', 'horse', 'ship', 'truck')

#### Dataloader
Combines a dataset and a sampler, and provides an iterable over the given dataset.

In [ ]:
trainloader = torch.utils.data.DataLoader(trainset, batch_size=80,
                                          shuffle=True, num_workers=2)
testloader = torch.utils.data.DataLoader(testset, batch_size=80,
                                         shuffle=False, num_workers=2)

Let us show some of the training images, for fun.

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

# functions to show an image
def imshow(img):
    img = img / 2 + 0.5     # unnormalize
    npimg = img.numpy()
    plt.imshow(np.transpose(npimg, (1, 2, 0)))
    plt.show()


# get some random training images
dataiter = iter(trainloader)
images, labels = dataiter.next()

print(images.size())

# show images
imshow(torchvision.utils.make_grid(images))
# print labels
print(' '.join('%5s' % classes[labels[j]] for j in range(4)))

**2. Define a Convolutional Neural Network**  
https://pytorch.org/tutorials/_images/mnist.png

In [ ]:
import torch.nn as nn
import torch.nn.functional as F

class Net(nn.Module):
    def __init__(self):
      super().__init__()
      self.conv1 = nn.Conv2d(in_channels=3, out_channels=6, kernel_size=5) #stride=1, padding=0
      self.pool1 = nn.MaxPool2d(kernel_size=2, stride=2)
      self.conv2 = nn.Conv2d(in_channels=6, out_channels=16, kernel_size=5)
      # pool
      self.fc1 = nn.Linear(16 * 5 * 5, 120)
      self.fc2 = nn.Linear(120, 84)
      self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
      # (b, 3, 32, 32)
      x = self.conv1(x) # => (b, 6, 28, 28)
      x = F.relu(x)
      x = self.pool1(x) # => (b, 6, 14, 14)

      x = self.pool1(F.relu(self.conv2(x))) # => (b, 16, 10, 10) => (b, 16, 5, 5)

      x = x.view(-1, 16 * 5 * 5) # => [b, 16 * 5 * 5]

      x = F.relu(self.fc1(x))
      x = F.relu(self.fc2(x))

      x = self.fc3(x)
      return x

net = Net()
net.cpu()

What is the CNN doing?
Add interrupts or print commands to check.

In [ ]:
dataiter = iter(trainloader)
images, labels = dataiter.next()
print(net(images).shape)   # Investigate the forward function

**3. Define a Loss function and optimizer**

Let's use a Classification Cross-Entropy loss and SGD with momentum.



In [ ]:
# Define loss and optimizer
import torch.optim as optim

criterion = nn.CrossEntropyLoss()

optimizer = optim.SGD(net.parameters(), lr=0.001, momentum=0.9)

**4. Train the network**

This is when things start to get interesting.
We simply have to loop over our data iterator, and feed the inputs to the
network and optimize.



In [ ]:
# Training loop


import time
t = time.time()

for epoch in range(2):

  running_loss = 0.0
  for i, data in enumerate(trainloader):
    # access data
    inputs, labels = data

    optimizer.zero_grad()
    # forward
    outputs = net(inputs)
     
    # loss
    loss = criterion(outputs, labels)

    # backward
    loss.backward()

    # update the weights
    optimizer.step()

    # print statistics
    running_loss += loss.item()
    if i % 100 == 99:  # printing every 2000 mini-batches/iterations
      print('[%d, %5d] loss: %.3f' %
                  (epoch + 1, i + 1, running_loss / 100))
      running_loss = 0.0


print(time.time() - t)

Let's quickly **save** our trained model:

In [ ]:
PATH = './cifar_net.pth'
torch.save(net.state_dict(), PATH)

**5. Test the network on the test data**


We have trained the network for 2 passes over the training dataset.
But we need to check if the network has learnt anything at all.

We will check this by predicting the class label that the neural network
outputs, and checking it against the ground-truth. If the prediction is
correct, we add the sample to the list of correct predictions.

Okay, first step. Let us display an image from the test set to get familiar.

In [ ]:
# Check the ground truth images
dataiter = iter(testloader)
images, labels = dataiter.next()

imshow(torchvision.utils.make_grid(images))
print('GroundTruth: ', ' '.join('%5s' % classes[labels[j]] for j in range(4)))

**Load** your trained model.

In [ ]:
net = Net()
net.load_state_dict(torch.load(PATH))

Compute outputs on test data.

In [ ]:
# Compute output
outputs = net(images)
print(outputs)
print(outputs.shape)

In [ ]:
max_val, predicted = torch.max(outputs, 1)    # torch.max returns the maximum value as well as the index
print(max_val, predicted)

# Print the predicted classes
print('Predicted: ', ' '.join('%5s' % classes[predicted[j]]
                              for j in range(4)))

Compute accuracy on the entire test set.

In [ ]:
# Loop over the test set and compute accuracy
correct = 0
total = 0
net.cuda()

with torch.no_grad():
    for data in testloader:
        images, labels = data[0].cuda(), data[1].cuda()

        outputs = net(images.cuda())

        max_val, predicted = torch.max(outputs.cuda(), 1)

        total += labels.size(0)
        correct += (predicted == labels).sum().item()

print('Accuracy: ', 100 * correct / total)

**Training on GPU**

Just like how you transfer a Tensor onto the GPU, you transfer the neural
net onto the GPU.

Let's first define our device as the first visible cuda device if we have
CUDA available:



In [ ]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

# Assuming that we are on a CUDA machine, this should print a CUDA device:

print(device)

Let's go back and make the necessary changes.

1. ``net.cuda()``

2. ``inputs, labels = data[0].cuda(), data[1].cuda()``

In [ ]:
# Define loss and optimizer
import torch.optim as optim

net.cuda() # <---------------------------------------- Put the model on the GPU
criterion = nn.CrossEntropyLoss()

optimizer = optim.SGD(net.parameters(), lr=0.001, momentum=0.9)

# Training loop
import time
t = time.time()


for epoch in range(2):

  running_loss = 0.0
  for i, data in enumerate(trainloader):
    # access data
    inputs, labels = data[0].cuda(), data[1].cuda() #<--------------------- put the inputs/labels on the gpu

    optimizer.zero_grad()
    # forward
    outputs = net(inputs)
     
    # loss
    loss = criterion(outputs, labels)

    # backward
    loss.backward()

    # update the weights
    optimizer.step()

    # print statistics
    running_loss += loss.item()
    if i % 100 == 99:  # printing every 2000 mini-batches/iterations
      print('[%d, %5d] loss: %.3f' %
                  (epoch + 1, i + 1, running_loss / 100))
      running_loss = 0.0


print(time.time() - t)

#### Exercises

What are the classes that performed well, and the classes that did
not perform well?
Calculate per class accuracy of your model by iterating with the testloader.

In [ ]:
# Compute per-class accuracy of the model
class_correct = list(0. for i in range(10))
class_total = list(0. for i in range(10))
with torch.no_grad():
    for data in testloader:
        images, labels = data[0].cuda(), data[1].cuda()
        outputs = net(images)
        _, predicted = torch.max(outputs, 1)
        c = (predicted == labels).squeeze()
        for i in range(4):    # assumes batch size of 4
            label = labels[i]
            class_correct[label] += c[i].item()
            class_total[label] += 1

for i in range(10):
    print('Accuracy of %5s : %2d %%' % (
        classes[i], 100 * class_correct[i] / class_total[i]))